/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRuntimeLogsRouteImport } from './routes/api/runtime-logs'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as ApiConnectorProjectsRouteImport } from './routes/api/connector/projects'
import { Route as ApiCliInstallerRouteImport } from './routes/api/cli/installer'
import { Route as ApiProjectsProjectIdExportRouteImport } from './routes/api/projects/$projectId/export'
import { Route as ApiProjectsProjectIdCloneRouteImport } from './routes/api/projects/$projectId/clone'
import { Route as ApiProjectsProjectIdDeploymentsDeploymentIdRouteImport } from './routes/api/projects/$projectId/deployments/$deploymentId'
import { Route as ApiConnectorProjectsProjectIdDeployRouteImport } from './routes/api/connector/projects/$projectId/deploy'
import { Route as ApiConnectorProjectsProjectIdFunctionsSyncRouteImport } from './routes/api/connector/projects/$projectId/functions/sync'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRuntimeLogsRoute = ApiRuntimeLogsRouteImport.update({
  id: '/api/runtime-logs',
  path: '/api/runtime-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiConnectorProjectsRoute = ApiConnectorProjectsRouteImport.update({
  id: '/api/connector/projects',
  path: '/api/connector/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliInstallerRoute = ApiCliInstallerRouteImport.update({
  id: '/api/cli/installer',
  path: '/api/cli/installer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsProjectIdExportRoute =
  ApiProjectsProjectIdExportRouteImport.update({
    id: '/api/projects/$projectId/export',
    path: '/api/projects/$projectId/export',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProjectsProjectIdCloneRoute =
  ApiProjectsProjectIdCloneRouteImport.update({
    id: '/api/projects/$projectId/clone',
    path: '/api/projects/$projectId/clone',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProjectsProjectIdDeploymentsDeploymentIdRoute =
  ApiProjectsProjectIdDeploymentsDeploymentIdRouteImport.update({
    id: '/api/projects/$projectId/deployments/$deploymentId',
    path: '/api/projects/$projectId/deployments/$deploymentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiConnectorProjectsProjectIdDeployRoute =
  ApiConnectorProjectsProjectIdDeployRouteImport.update({
    id: '/$projectId/deploy',
    path: '/$projectId/deploy',
    getParentRoute: () => ApiConnectorProjectsRoute,
  } as any)
const ApiConnectorProjectsProjectIdFunctionsSyncRoute =
  ApiConnectorProjectsProjectIdFunctionsSyncRouteImport.update({
    id: '/$projectId/functions/sync',
    path: '/$projectId/functions/sync',
    getParentRoute: () => ApiConnectorProjectsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/app': typeof AuthenticatedAppRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/runtime-logs': typeof ApiRuntimeLogsRoute
  '/api/cli/installer': typeof ApiCliInstallerRoute
  '/api/connector/projects': typeof ApiConnectorProjectsRouteWithChildren
  '/api/projects/$projectId/clone': typeof ApiProjectsProjectIdCloneRoute
  '/api/projects/$projectId/export': typeof ApiProjectsProjectIdExportRoute
  '/api/connector/projects/$projectId/deploy': typeof ApiConnectorProjectsProjectIdDeployRoute
  '/api/projects/$projectId/deployments/$deploymentId': typeof ApiProjectsProjectIdDeploymentsDeploymentIdRoute
  '/api/connector/projects/$projectId/functions/sync': typeof ApiConnectorProjectsProjectIdFunctionsSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/app': typeof AuthenticatedAppRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/runtime-logs': typeof ApiRuntimeLogsRoute
  '/api/cli/installer': typeof ApiCliInstallerRoute
  '/api/connector/projects': typeof ApiConnectorProjectsRouteWithChildren
  '/api/projects/$projectId/clone': typeof ApiProjectsProjectIdCloneRoute
  '/api/projects/$projectId/export': typeof ApiProjectsProjectIdExportRoute
  '/api/connector/projects/$projectId/deploy': typeof ApiConnectorProjectsProjectIdDeployRoute
  '/api/projects/$projectId/deployments/$deploymentId': typeof ApiProjectsProjectIdDeploymentsDeploymentIdRoute
  '/api/connector/projects/$projectId/functions/sync': typeof ApiConnectorProjectsProjectIdFunctionsSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/runtime-logs': typeof ApiRuntimeLogsRoute
  '/api/cli/installer': typeof ApiCliInstallerRoute
  '/api/connector/projects': typeof ApiConnectorProjectsRouteWithChildren
  '/api/projects/$projectId/clone': typeof ApiProjectsProjectIdCloneRoute
  '/api/projects/$projectId/export': typeof ApiProjectsProjectIdExportRoute
  '/api/connector/projects/$projectId/deploy': typeof ApiConnectorProjectsProjectIdDeployRoute
  '/api/projects/$projectId/deployments/$deploymentId': typeof ApiProjectsProjectIdDeploymentsDeploymentIdRoute
  '/api/connector/projects/$projectId/functions/sync': typeof ApiConnectorProjectsProjectIdFunctionsSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/login'
    | '/app'
    | '/dashboard'
    | '/api/runtime-logs'
    | '/api/cli/installer'
    | '/api/connector/projects'
    | '/api/projects/$projectId/clone'
    | '/api/projects/$projectId/export'
    | '/api/connector/projects/$projectId/deploy'
    | '/api/projects/$projectId/deployments/$deploymentId'
    | '/api/connector/projects/$projectId/functions/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/login'
    | '/app'
    | '/dashboard'
    | '/api/runtime-logs'
    | '/api/cli/installer'
    | '/api/connector/projects'
    | '/api/projects/$projectId/clone'
    | '/api/projects/$projectId/export'
    | '/api/connector/projects/$projectId/deploy'
    | '/api/projects/$projectId/deployments/$deploymentId'
    | '/api/connector/projects/$projectId/functions/sync'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/callback'
    | '/login'
    | '/_authenticated/app'
    | '/_authenticated/dashboard'
    | '/api/runtime-logs'
    | '/api/cli/installer'
    | '/api/connector/projects'
    | '/api/projects/$projectId/clone'
    | '/api/projects/$projectId/export'
    | '/api/connector/projects/$projectId/deploy'
    | '/api/projects/$projectId/deployments/$deploymentId'
    | '/api/connector/projects/$projectId/functions/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  LoginRoute: typeof LoginRoute
  ApiRuntimeLogsRoute: typeof ApiRuntimeLogsRoute
  ApiCliInstallerRoute: typeof ApiCliInstallerRoute
  ApiConnectorProjectsRoute: typeof ApiConnectorProjectsRouteWithChildren
  ApiProjectsProjectIdCloneRoute: typeof ApiProjectsProjectIdCloneRoute
  ApiProjectsProjectIdExportRoute: typeof ApiProjectsProjectIdExportRoute
  ApiProjectsProjectIdDeploymentsDeploymentIdRoute: typeof ApiProjectsProjectIdDeploymentsDeploymentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runtime-logs': {
      id: '/api/runtime-logs'
      path: '/api/runtime-logs'
      fullPath: '/api/runtime-logs'
      preLoaderRoute: typeof ApiRuntimeLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/connector/projects': {
      id: '/api/connector/projects'
      path: '/api/connector/projects'
      fullPath: '/api/connector/projects'
      preLoaderRoute: typeof ApiConnectorProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/installer': {
      id: '/api/cli/installer'
      path: '/api/cli/installer'
      fullPath: '/api/cli/installer'
      preLoaderRoute: typeof ApiCliInstallerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$projectId/export': {
      id: '/api/projects/$projectId/export'
      path: '/api/projects/$projectId/export'
      fullPath: '/api/projects/$projectId/export'
      preLoaderRoute: typeof ApiProjectsProjectIdExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$projectId/clone': {
      id: '/api/projects/$projectId/clone'
      path: '/api/projects/$projectId/clone'
      fullPath: '/api/projects/$projectId/clone'
      preLoaderRoute: typeof ApiProjectsProjectIdCloneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$projectId/deployments/$deploymentId': {
      id: '/api/projects/$projectId/deployments/$deploymentId'
      path: '/api/projects/$projectId/deployments/$deploymentId'
      fullPath: '/api/projects/$projectId/deployments/$deploymentId'
      preLoaderRoute: typeof ApiProjectsProjectIdDeploymentsDeploymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connector/projects/$projectId/deploy': {
      id: '/api/connector/projects/$projectId/deploy'
      path: '/$projectId/deploy'
      fullPath: '/api/connector/projects/$projectId/deploy'
      preLoaderRoute: typeof ApiConnectorProjectsProjectIdDeployRouteImport
      parentRoute: typeof ApiConnectorProjectsRoute
    }
    '/api/connector/projects/$projectId/functions/sync': {
      id: '/api/connector/projects/$projectId/functions/sync'
      path: '/$projectId/functions/sync'
      fullPath: '/api/connector/projects/$projectId/functions/sync'
      preLoaderRoute: typeof ApiConnectorProjectsProjectIdFunctionsSyncRouteImport
      parentRoute: typeof ApiConnectorProjectsRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiConnectorProjectsRouteChildren {
  ApiConnectorProjectsProjectIdDeployRoute: typeof ApiConnectorProjectsProjectIdDeployRoute
  ApiConnectorProjectsProjectIdFunctionsSyncRoute: typeof ApiConnectorProjectsProjectIdFunctionsSyncRoute
}

const ApiConnectorProjectsRouteChildren: ApiConnectorProjectsRouteChildren = {
  ApiConnectorProjectsProjectIdDeployRoute:
    ApiConnectorProjectsProjectIdDeployRoute,
  ApiConnectorProjectsProjectIdFunctionsSyncRoute:
    ApiConnectorProjectsProjectIdFunctionsSyncRoute,
}

const ApiConnectorProjectsRouteWithChildren =
  ApiConnectorProjectsRoute._addFileChildren(ApiConnectorProjectsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CallbackRoute: CallbackRoute,
  LoginRoute: LoginRoute,
  ApiRuntimeLogsRoute: ApiRuntimeLogsRoute,
  ApiCliInstallerRoute: ApiCliInstallerRoute,
  ApiConnectorProjectsRoute: ApiConnectorProjectsRouteWithChildren,
  ApiProjectsProjectIdCloneRoute: ApiProjectsProjectIdCloneRoute,
  ApiProjectsProjectIdExportRoute: ApiProjectsProjectIdExportRoute,
  ApiProjectsProjectIdDeploymentsDeploymentIdRoute:
    ApiProjectsProjectIdDeploymentsDeploymentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
